### ISSUE TITLE
Implementation for VK_KHR_ray_tracing

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/dawn-ray-tracing#3]
Currently, the VK_NV_ray_tracing extension for Vulkan is used.
A sample implementation for VK_KHR_ray_tracing is in progress [here](https://github.com/maierfelix/VK_KHR_ray_tracing) and will later be added to this project.

**Comment by oscarbg** [comment]
nice.. will keep an eye!

**Comment by yyc-git** [comment]
great!
